import "./globals.css";

import type { Metadata } from "next";
import { Zen_Tokyo_Zoo } from "next/font/google";

const zen = Zen_Tokyo_Zoo({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={zen.className}>{children}</body>
    </html>
  );
}
